### ISSUE TITLE
Not able to load lupo in windbg

### ISSUE THREAD

**Issue by archanchoudhury** [vithakur/lupo#1]
Hi, As per the specified suggestion tried to load Lupo in Windbg after the breakpoint of the program, but it didn't run. Attached are the snap. Any suggestions?
![image](https://user-images.githubusercontent.com/51078911/86055990-5ac72b00-ba7a-11ea-8f2a-8f56e4b84d14.png)
![Capture2](https://user-images.githubusercontent.com/51078911/86056020-64509300-ba7a-11ea-806b-3d7e62771c0a.JPG)

**Comment by malienist** [comment]
Hi @archanchoudhury 
I haven't encountered this problem yet, I'll have a look and see if I can find a solution. Can you share some more info about your VM (arch, OS version, WinDbg version etc)?

**Comment by archanchoudhury** [comment]
Hi @vithakur 
I am using Win-10 Evaluation Copy, it's a 64bit OS. I have downloaded it from here- https://download.microsoft.com/download/1/c/3/1c3d5161-d9e9-4e4b-9b43-b70fe8be268c/windowssdk/winsdksetup.exe

For WinDbg I have downloaded it from here- https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk/
If I download it from MS Store, It will be installed in WindowsApps, and despite claiming it's ownership we can't paste any file inside it..

I do have WinDbg both version installed into this OS- X64 and X86. And I tried with both(pasted the lupo files in both the location before running), but same kinda error. My current WinDbg version is- 10.0.19041.1 X86 and 10.0.19041.1 AMD64

**Comment by malienist** [comment]
Hi @archanchoudhury - I know what the problem is. Your machine is most probably missing some VC++ dependencies. The quickest way to resolve that would be to install a copy of Visual Studio Community from here: https://visualstudio.microsoft.com/downloads/ and select all the C++ components. 
Alternatively, you can also try installing the VC++ redist. After you've done that, you should be able to load Lupo into WinDbg. Let me know how you go.
